language: node_js
node_js:
  - "10"
cache: npm
addons:
  postgresql: "9.4"
services:
  - redis-server
env:
  global:
    - TEST_DATABASE_URL="postgresql://postgres@localhost/test
script: npm test || npm test
