language: node_js
node_js:
    - "8"
    - "9"

env:
    global:
	- CC_TEST_REPORTER_ID=413841d521d7e9f24fb2e43180025f1546b84164477103cf138c2a4169f0c4e3

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

after_success:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
