language: node_js
node_js:
  - "10"
cache: npm
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
env:
  global:
    - TEST_DATABASE_URL="postgresql://testuser:testpassword@localhost/test
before_script:
  - psql --version
  - echo /etc/postgresql/9.4/main/pg_hba.conf
  - psql -c "CREATE ROLE testuser LOGIN CREATEDB PASSWORD 'testpassword';" -U postgres
script: npm test || npm test
