language: node_js
node_js:
  - "10"
cache: npm
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
env:
  global:
    - TEST_DATABASE_URL="postgresql://testuser:testpassword@localhost/testdb"
before_script:
  - psql --version
  - psql -c "CREATE ROLE testuser LOGIN CREATEDB PASSWORD 'testpassword';" -U postgres
  - psql -c "CREATE DATABASE test;" ${TEST_DATABASE_URL/testdb/postgres}
script: npm test || npm test
