version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: 'postgres://smartbirds:secret@db:5432/smartbirds'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    volumes:
      - ./uploads/files:/app/uploads/files
      - ./uploads/tmp:/app/uploads/tmp
      - ./public:/app/public
      - ./log:/app/log
  db:
    build: docker/db
    environment:
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_USER: 'smartbirds'
    ports:
      - "5432:5432"
  redis:
    build: docker/redis
    ports:
      - "6379:6379"
