web:
  build: .
  volumes:
    - .:/usr/src/app
  links:
    - db
  ports:
    - "5000:5000"
  environment:
    DATABASE_URL: 'postgres://smartbirds:secret@db:5432/smartbirds'

db:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: 'secret'
    POSTGRES_USER: 'smartbirds'
  ports:
    - "5432:5432"

dbadmin:
  image: adminer
  links:
    - db
  ports:
    - "8080:8080"
