# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sqlite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        redis-version: [3, latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis ${{ matrix.redis-version }}
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: ${{ matrix.redis-version }}

      - run: npm ci
      - run: npm run test:sqlite
        env:
          CI: true

  postgres:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        redis-version: [3, latest]
        postgresql-version: [9.4-alpine, latest]

    steps:
      - uses: actions/checkout@v3

      - name: Start Postgres ${{ matrix.postgresql-version }}
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ matrix.postgresql-version }}
          postgresql db: testdb
          postgresql user: testuser
          postgresql password: testpass

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis ${{ matrix.redis-version }}
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: ${{ matrix.redis-version }}

      - run: npm ci
      - run: npm run test:pg
        env:
          CI: true
          TEST_DATABASE_URL: 'postgres://testuser:testpass@localhost/testdb'

  dbschema:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        redis-version: [3]
        postgresql-version: [9.4-alpine]

    steps:
      - uses: actions/checkout@v3

      - name: Start Postgres ${{ matrix.postgresql-version }}
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ matrix.postgresql-version }}
          postgresql db: testdb
          postgresql user: testuser
          postgresql password: testpass

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis ${{ matrix.redis-version }}
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: ${{ matrix.redis-version }}

      - run: npm ci
      - run: npm run test:dbschema
        env:
          CI: true
          TEST_DATABASE_URL: 'postgres://testuser:testpass@localhost/testdb'
